insert into _user values (1, 'admin', 'admin');
insert into _schedule values (1, 1, 'Основная тренировка');
insert into _workout values (1, 'Спина');
insert into _workout values (2, 'Плечи');
insert into _workout values (3, 'Кардио');
insert into _workout values (4, 'Ноги');
insert into _workout values (5, 'Руки');
insert into _workout values (6, 'Пресс (+Грудь)');
insert into _exercise values (1, 'BACK', 'Тяга гантели в наклоне', '12,10,10,8,6', 16, '');
insert into _exercise values (2, 'BACK', 'Тяга в наклоне одной гантелью', '12,10,10,8,6', 16, '');
insert into _exercise values (3, 'SHOULDERS', 'Жим гантелей стоя', '12,10,10,8', 6, '');
insert into _exercise values (4, 'SHOULDERS', 'Разведение гантелей в стороны', '12,10,10', 6, '');
insert into _exercise values (5, 'SHOULDERS', 'Разведение гантелей в наклоне', '12,10,10', 6, '');
insert into _exercise values (6, 'SHOULDERS', 'Шраги гантелями', '12,10,10,8', 16, '');
insert into _exercise values (7, 'LEGS', 'Приседания с гантелями', '12,10,10,8', 16, '');
insert into _exercise values (8, 'LEGS', 'Становая тяга гантелями на прямых ногах', '12,10,10,8', 16, '');
insert into _exercise values (9, 'LEGS', 'Выпады с гантелями', '12,10,10,8', 6, '');
insert into _exercise values (10, 'LEGS', 'Подъём на икры стоя с гантелями', '12,10', 16, '');
insert into _exercise values (11, 'ARMS', 'Сгибание на бицепс стоя', '10,10,10', 6, '');
insert into _exercise values (12, 'ARMS', 'Поочерёдное сгибание рук хватом «молоток»', '10,10', 6, '');
insert into _exercise values (13, 'ARMS', 'Сгибание рук сидя в наклоне', '10,10,10', 6, '');
insert into _exercise values (14, 'ARMS', 'Разгибание руки назад с гантелью в наклоне', '12,12,12', 6, '');
insert into _exercise values (15, 'ARMS', 'Разгибание одной рукой с гантелью из-за головы стоя', '12,12,12', 6, '');
insert into _exercise values (16, null, 'Кардио', null, 0, '');
insert into _exercise values (17, null, 'Отжимания', null, 0, '');
insert into _exercise values (18, null, 'Пресс', null, 0, '');